
drop table pupils if exists;
drop table users if exists;

create table pupils (id bigint generated by default as identity (start with 1), firstName varchar(255), lastName varchar(255), primary key (id));
create table users (id bigint generated by default as identity (start with 1), password varchar(255), username varchar(255), primary key (id));